
[project]
name = "homework5"
version = "0.1.0"
description = "ML ZoomCamp Homework 5"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "uvicorn>=0.34.0",
    "scikit-learn>=1.6.1",
]
